server:
  port: 8080

# 四大金刚
spring:
  mail:
    host: smtp.qq.com   # 设置邮箱主机(服务商),这里使用QQ邮件服务器
    username: 1247780087@qq.com  # 设置用户名，我们需要更改
    password: zpzmshrkwdplfdje # 设置授权码，该处的密码是QQ邮箱开启SMTP的授权码而非QQ密码，我们需要更改
    properties:
      mail:
        smtp:
          auth: true  # 必须进行授权认证，它的目的就是阻止他人任意乱发邮件
          starttls: #SMTP加密方式:连接到一个TLS保护连接
            enable: true
            required: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    username: root
    password: 51823
    url: jdbc:mysql:///pethome
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8

#  别名和mapper映射文件位置
mybatis:
  mapper-locations: classpath:cn/raths/*/mapper/*Mapper.xml
  type-aliases-package: cn.raths.*.domain,cn.raths.*.query
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    cn.raths: trace

