server:
  port: 8080

# 四大金刚
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    username: root
    password: 51823
    url: jdbc:mysql:///pethome
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-wait: 2000ms
        min-idle: 2
        max-idle: 8

#  别名和mapper映射文件位置
mybatis:
  mapper-locations: classpath:cn/raths/*/mapper/*Mapper.xml
  type-aliases-package: cn.raths.org.domain

# 日志
logging:
  level:
    cn.raths: trace

