server:
  port: 8080

# 四大金刚
spring:
  datasource:
    username: root
    password: 51823
    url: jdbc:mysql:///pethome
    driver-class-name: com.mysql.jdbc.Driver

#  别名和mapper映射文件位置
mybatis:
  mapper-locations: classpath:cn/raths/*/mapper/*Mapper.xml
  type-aliases-package: cn.raths.org.domain

# 日志
logging:
  level:
    cn.raths: trace